server:
  port: 8080

spring:
  application:
    name: web

  config:
    import: configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus