server:
  port: 8079
spring:
  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      authorizationserver:
        client:
          demo-client:
            require-authorization-consent: true
            registration:
              client-id: client
              client-secret: "secret"
              authorization-grant-types: client_credentials,authorization_code,refresh_token
              redirect-uris: http://127.0.0.1:8080/login/oauth2/code/reg-client
              scopes: user.read,user.write,openid
              client-authentication-methods: client_secret_basic
logging:
  level:
    org:
      springframework:
        security: trace